Fix relative imports after pip installation (#11)
These namespace relative imports work in chumpy tests, but were causing import errors like this one:

```
  File "/home/circleci/repo/blmath/geometry/transform/test_composite.py", line 172, in test_forward_reverse_equivalence
    transform.rotate(np.array([1., 2., 3.]))
  File "/home/circleci/repo/blmath/geometry/transform/composite.py", line 237, in rotate
    from blmath.geometry.transform.rodrigues import as_rotation_matrix
  File "/home/circleci/repo/blmath/geometry/transform/rodrigues.py", line 2, in <module>
    import chumpy as ch
  File "/home/circleci/repo/venv/lib/python2.7/site-packages/chumpy/__init__.py", line 1, in <module>
    from .ch import *
  File "/home/circleci/repo/venv/lib/python2.7/site-packages/chumpy/ch.py", line 1310, in <module>
    from . import ch_ops
  File "/home/circleci/repo/venv/lib/python2.7/site-packages/chumpy/ch_ops.py", line 47, in <module>
    from . import ch
ImportError: cannot import name ch
```